menu:
  首页: / 
  归档: /archives
  关于: /about
  订阅: /atom.xml

# gitment
gitment: false
gitment_owner:
gitment_repo:
gitment_client_id:
gitment_client_secret:

# gitalk
gitalk: false
gitalk_owner:
gitalk_admin: []
gitalk_repo:
gitalk_client_id:
gitalk_client_secret:

# valine comment
valine: true
leancloud_id: NDkvUjIj6j0I0dC8Y4h9j9eb-MdYXbMMI
leancloud_key: KTkph3xn5SF2fw0wgpapS63n

# disqus comment
disqus: false
disqus_shortname:

# google analytics
googleTrackId: 139152590

# whether to show read more button when showing article in excerpt in main page
read_more: true
